exoverride_controller:
    resource: "@CPASimUSanteExoverrideBundle/Controller/ExoverrideController.php"
    type: annotation
    prefix: /

admin_paper:
    resource: "routing/admin/paper.yml"
    prefix:   /admin/paper
