cpasimusante_get_user_in_ws:
    pattern:  /usersinws/{wslist}
    defaults: { _controller: "CPASimUSanteExoverrideBundle:Paper:getUsersInWorkspace" }
    options:
        expose: true

#controller for gathering data for displaying the radar graph
ujm_paper_export_all_results_json:
    pattern:  /export/all_results/json/ul/{userdata}/rl/{resourcedata}
    defaults: { _controller: "CPASimUSanteExoverrideBundle:Paper:getResultExercisesJson" }
    options:
        expose: true

#show results statistics as html
ujm_paper_show_all_results:
    pattern:  /show/all_results/html/{resourcedata}
    defaults: { _controller: "CPASimUSanteExoverrideBundle:Paper:getResultExercisesHtml" }
    options:
        expose: true

#export results statistics as csv
ujm_paper_export_all_results_cvs:
    pattern:  /export/all_results/csv/{resourcedata}
    defaults: { _controller: "CPASimUSanteExoverrideBundle:Paper:getResultExercisesCsv" }
    options:
        expose: true

ujm_paper_export_complete_results:
    pattern:  /export/complete_results/csv/{exerciseId}
    defaults: { _controller: "CPASimUSanteExoverrideBundle:Paper:exportResCompleteCSV" }

ujm_paper_show_radar:
    pattern:  /show/frame
    defaults: { _controller: "CPASimUSanteExoverrideBundle:Paper:openRadar" }
    options:
        expose: true


ujm_paper_show_all_results_test:
    pattern:  /show/all_results/htmltest/{resourcedata}
    defaults: { _controller: "CPASimUSanteExoverrideBundle:Paper:getResultExercisesHtmltest" }
    options:
        expose: true

ujm_paper_export_all_results_cvs_test:
    pattern:  /export/all_results/csvtest/{resourcedata}
    defaults: { _controller: "CPASimUSanteExoverrideBundle:Paper:getResultExercisesCsvtest" }
    options:
        expose: true

