ujm_paper_export_complete_results:
    pattern:  /export/complete_results/csv/{exerciseId}
    defaults: { _controller: "CPASimUSanteExoverrideBundle:Paper:exportResCompleteCSV" }

ujm_paper_export_all_results:
    pattern:  /export/all_results/html
    defaults: { _controller: "CPASimUSanteExoverrideBundle:Paper:getResultExercicesHtml" }