cpasimusante_statwidget_config:
    pattern:  /configwidget/{widgetInstance}
    defaults: { _controller: "CPASimUSanteExoverrideBundle:ExoverrideWidget:userStatWidgetConfigureForm" }
    options:
        expose: true