<?php

namespace CPASimUSante\ExoverrideBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExoverrideStatConfigDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExoverrideStatConfigDataRepository extends EntityRepository
{
}
