<?php

namespace CPASimUSante\ExoverrideBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UJM\ExoBundle\Repository\ResponseRepository as BaseRepository;

/**
 * PaperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseRepository extends BaseRepository
{
    /**
     *
     * @return array
     */
    public function getQueryExerciseAllResponsesForAllUsers($exoId, $order)
    {
        $qb = $this->createQueryBuilder('r');
        $qb->join('r.paper', 'p')
            ->join('p.exercise', 'e')
            ->where('e.id = ?1')
            ->andWhere('p.interupt =  ?2')
//            ->orderBy($order, 'ASC')
            ->setParameters(array(1 => $exoId, 2 => 0));
        return $qb->getQuery();
    }

    public function getExerciseAllResponsesForAllUsersIterator($exoId, $order)
    {
        return $this->getQueryExerciseAllResponsesForAllUsers($exoId, $order)->iterate();
    }

    public function getExerciseAllResponsesForAllUsersQuery($exoId, $order)
    {
        return $this->getQueryExerciseAllResponsesForAllUsers($exoId, $order)->getResult();
    }
}
